export const hunters = [
    {
        "name": "Сон Джин Ву",
        "gender": "M",
        "rank": "S",
        "img": "/assets/characters/jinwoo.webp",
        "guild": "Аджин",
        "age": 24,
        "status": "Активен",
        "loc": "Подземелье S-ранга",
        "contact": "Ю Джин Хо",
        "bio": "Единственный охотник, прошедший путь от E до S ранга."
    },
    {
        "name": "Ча Хэ Ин",
        "gender": "F",
        "rank": "S",
        "img": "/assets/characters/cha-hae.webp",
        "guild": "Охотники",
        "age": 23,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Сон Джин-Ву",
        "bio": "Заместитель гильдии Охотников, обладающая уникальным обонянием."
    },
    {
        "name": "Ко Гун Хи",
        "gender": "M",
        "rank": "S",
        "img": "/assets/characters/gunhee.webp",
        "guild": "Ассоциация",
        "age": 70,
        "status": "В отставке",
        "loc": "Сеул",
        "contact": "Сон Джин-Ву",
        "bio": "Председатель Корейской ассоциации охотников."
    },
    {
        "name": "Селена Рид",
        "gender": "F",
        "rank": "S",
        "img": "/assets/characters/selena-reed.webp",
        "guild": "Нет",
        "age": 30,
        "status": "Активен",
        "loc": "США",
        "contact": "Томас Андре",
        "bio": "Охотник национального уровня, известная своей магической мощью."
    },
    {
        "name": "Леннарт Нирманн",
        "gender": "M",
        "rank": "S",
        "img": "/assets/characters/lennart.webp",
        "guild": "Richter",
        "age": 30,
        "status": "Активен",
        "loc": "Германия",
        "contact": "Томас Андре",
        "bio": "Сильнейший охотник Германии, мастер защиты и мощных контратак."
    },
    {
        "name": "Лилия Шнайдер",
        "gender": "F",
        "rank": "S",
        "img": "/assets/characters/lilia-schneider.webp",
        "guild": "Richter",
        "age": 27,
        "status": "Активен",
        "loc": "Германия",
        "contact": "Эмили Браун",
        "bio": "Мастер стихийной магии, специализирующаяся на управлении льдом."
    },
    {
        "name": "Кристофер Рид",
        "gender": "M",
        "rank": "S",
        "img": "/assets/characters/christopher.webp",
        "guild": "Нет",
        "age": 35,
        "status": "Погиб",
        "loc": "США",
        "contact": "Нет данных",
        "bio": "Один из пяти охотников национального уровня, обладавший невероятной физической мощью."
    },
    {
        "name": "Эмили Браун",
        "gender": "F",
        "rank": "S",
        "img": "/assets/characters/emily-brown.webp",
        "guild": "Richter",
        "age": 28,
        "status": "Активен",
        "loc": "Германия",
        "contact": "Леннарт Нирманн",
        "bio": "Элитный маг поддержки, признанная на международном уровне."
    },
    {
        "name": "Гото Рюджи",
        "gender": "M",
        "rank": "S",
        "img": "/assets/characters/goto-ryuji.webp",
        "guild": "Драконы",
        "age": 35,
        "status": "Погиб",
        "loc": "Остров Чеджу",
        "contact": "Нет данных",
        "bio": "Сильнейший охотник Японии."
    },
    {
        "name": "Лю Чжи Ган",
        "gender": "M",
        "rank": "S",
        "img": "/assets/characters/liu-zhigang.webp",
        "guild": "Нет",
        "age": 36,
        "status": "Активен",
        "loc": "Китай",
        "contact": "Нет данных",
        "bio": "Сильнейший охотник Китая, один из пяти охотников национального уровня."
    },
    {
        "name": "Канаэ Тавара",
        "gender": "F",
        "rank": "S",
        "img": "/assets/characters/kanae-tawara.webp",
        "guild": "Драконы",
        "age": 29,
        "status": "Активен",
        "loc": "Япония",
        "contact": "Гото Рюджи",
        "bio": "Сильнейшая женщина-охотник Японии, мастер клинка."
    },
    {
        "name": "Чхве Чжон Ин",
        "gender": "M",
        "rank": "A",
        "img": "/assets/characters/jong.webp",
        "guild": "Охотники",
        "age": 28,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Ча Хэ Ин",
        "bio": "Маг огня высшего уровня."
    },
    {
        "name": "Пэк Юн Хо",
        "gender": "M",
        "rank": "A",
        "img": "/assets/characters/baek.webp",
        "guild": "Белые Тигры",
        "age": 30,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Сон Джин-Ву",
        "bio": "Мастер гильдии, способный принимать форму зверя."
    },
    {
        "name": "Лим Тэ Гю",
        "gender": "M",
        "rank": "A",
        "img": "/assets/characters/lim-tae.webp",
        "guild": "Кулак",
        "age": 32,
        "status": "Активен",
        "loc": "База гильдии",
        "contact": "Нет данных",
        "bio": "Мастер стрельбы из лука."
    },
    {
        "name": "Кан Хе Рин",
        "gender": "F",
        "rank": "A",
        "img": "/assets/characters/kang-herin.webp",
        "guild": "Охотники",
        "age": 27,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Нет данных",
        "bio": "Маг высшего уровня поддержки."
    },
    {
        "name": "Ким Чул",
        "gender": "M",
        "rank": "A",
        "img": "/assets/characters/kim-chul.webp",
        "guild": "Рыцари",
        "age": 26,
        "status": "Погиб",
        "loc": "Красные врата",
        "contact": "Хван Дон Су",
        "bio": "Танк высокого уровня."
    },
    {
        "name": "Ю Су-Хен",
        "gender": "F",
        "rank": "B",
        "img": "/assets/characters/yoo-soo-hyun.webp",
        "guild": "Охотники",
        "age": 23,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Ча Хэ Ин",
        "bio": "Охотник гильдии Охотники, специализирующаяся на поддержке и защите."
    },
    {
        "name": "Ли Джу Хи",
        "gender": "F",
        "rank": "B",
        "img": "/assets/characters/lee-joo.webp",
        "guild": "Ассоциация",
        "age": 21,
        "status": "Активен",
        "loc": "Госпиталь",
        "contact": "Сон Джин-Ву",
        "bio": "Целитель, близкий друг Джин-Ву."
    },
    {
        "name": "Ю Джин Хо",
        "gender": "M",
        "rank": "D",
        "img": "/assets/characters/jinho.webp",
        "guild": "Аджин",
        "age": 22,
        "status": "Активен",
        "loc": "Офис гильдии",
        "contact": "Сон Джин-Ву",
        "bio": "Верный соратник и вице-мастер гильдии."
    },
    {
        "name": "Хван Дон Су",
        "gender": "M",
        "rank": "A",
        "img": "/assets/characters/hwang-dong.webp",
        "guild": "Охотники (США)",
        "age": 31,
        "status": "Погиб",
        "loc": "Неизвестно",
        "contact": "Хван Дон Сок",
        "bio": "Охотник, ищущий мести."
    },
    {
        "name": "Пак Су Джин",
        "gender": "F",
        "rank": "A",
        "img": "/assets/characters/park-sujin.webp",
        "guild": "Белые Тигры",
        "age": 26,
        "status": "Активен",
        "loc": "База гильдии",
        "contact": "Нет данных",
        "bio": "Специалист по магической поддержке и защите."
    },
    {
        "name": "Чон Со Ён",
        "gender": "F",
        "rank": "C",
        "img": "/assets/characters/jeong-soyeon.webp",
        "guild": "Нет",
        "age": 22,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Начинающий охотник поддержки."
    },
    {
        "name": "Кан Тэ Шик",
        "gender": "M",
        "rank": "B",
        "img": "/assets/characters/kang-tae.webp",
        "guild": "Ассоциация",
        "age": 29,
        "status": "Погиб",
        "loc": "Тюрьма",
        "contact": "Нет данных",
        "bio": "Охотник-убийца."
    },
    {
        "name": "Сон Ки Хун",
        "gender": "M",
        "rank": "C",
        "img": "/assets/characters/song-kihun.webp",
        "guild": "Нет",
        "age": 34,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Обычный охотник поддержки."
    },
    {
        "name": "Хан Джи Вон",
        "gender": "F",
        "rank": "C",
        "img": "/assets/characters/han-jiwon.webp",
        "guild": "Нет",
        "age": 20,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Специалист по разведке местности."
    },
    {
        "name": "Пак Хи Джин",
        "gender": "F",
        "rank": "B",
        "img": "/assets/characters/park-hee.webp",
        "guild": "Охотники",
        "age": 25,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Ча Хэ Ин",
        "bio": "Маг-поддержка."
    },
    {
        "name": "Ли Сон А",
        "gender": "F",
        "rank": "A",
        "img": "/assets/characters/lee-sona.webp",
        "guild": "Ассоциация",
        "age": 28,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Охотник, специализирующийся на дальнем магическом уроне."
    },
    {
        "name": "Хван Дон Сок",
        "gender": "M",
        "rank": "C",
        "img": "/assets/characters/hwang-dons.webp",
        "guild": "Нет",
        "age": 38,
        "status": "Погиб",
        "loc": "Подземелье",
        "contact": "Хван Дон Су",
        "bio": "Лидер группы рейдеров."
    },
    {
        "name": "Юн Гён Хван",
        "gender": "M",
        "rank": "C",
        "img": "/assets/characters/yoon_gyun.webp",
        "guild": "Нет",
        "age": 27,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Охотник среднего ранга."
    },
    {
        "name": "О Юн А",
        "gender": "F",
        "rank": "C",
        "img": "/assets/characters/oh-yuna.webp",
        "guild": "Нет",
        "age": 23,
        "status": "Активен",
        "loc": "Подземелье",
        "contact": "Нет данных",
        "bio": "Охотник среднего звена."
    },
    {
        "name": "Ким Сан Шик",
        "gender": "M",
        "rank": "C",
        "img": "/assets/characters/sang-shik.webp",
        "guild": "Нет",
        "age": 33,
        "status": "Погиб",
        "loc": "Подземелье",
        "contact": "Хван Дон Сок",
        "bio": "Опытный ветеран."
    },
    {
        "name": "Чхве Ю Ри",
        "gender": "F",
        "rank": "A",
        "img": "/assets/characters/choi-yuri.webp",
        "guild": "Рыцари",
        "age": 25,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Нет данных",
        "bio": "Эксперт по обнаружению скрытых угроз."
    },
    {
        "name": "Сон Ын Джи",
        "gender": "F",
        "rank": "C",
        "img": "/assets/characters/song-eunji.webp",
        "guild": "Нет",
        "age": 21,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Ассистент в рейдах."
    },
    {
        "name": "Ким Ми На",
        "gender": "F",
        "rank": "A",
        "img": "/assets/characters/kim-mina.webp",
        "guild": "Охотники",
        "age": 24,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Нет данных",
        "bio": "Мастер ближнего боя с использованием кинжалов."
    },
    {
        "name": "Пэк Ми Хо",
        "gender": "F",
        "rank": "B",
        "img": "/assets/characters/mi-ho.webp",
        "guild": "Белые Тигры",
        "age": 24,
        "status": "Активен",
        "loc": "База гильдии",
        "contact": "Пэк Юн Хо",
        "bio": "Элитный разведчик."
    },
    {
        "name": "Ли Мин Сон",
        "gender": "M",
        "rank": "C",
        "img": "/assets/characters/min-sung.webp",
        "guild": "Нет",
        "age": 26,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Охотник широкого профиля."
    },
    {
        "name": "Чо Гю Хван",
        "gender": "M",
        "rank": "C",
        "img": "/assets/characters/cho-gyu.webp",
        "guild": "Нет",
        "age": 29,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Охотник, специализирующийся на разведке и тактическом отступлении."
    },
    {
        "name": "Ким Бо Ра",
        "gender": "F",
        "rank": "C",
        "img": "/assets/characters/kim-bora.webp",
        "guild": "Нет",
        "age": 24,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Боец поддержки."
    },
    {
        "name": "Чжон Е Рин",
        "gender": "F",
        "rank": "B",
        "img": "/assets/characters/ye-rin.webp",
        "guild": "Охотники",
        "age": 22,
        "status": "Активен",
        "loc": "Штаб-квартира",
        "contact": "Ча Хэ Ин",
        "bio": "Специалист по барьерам."
    },
    {
        "name": "Квак До Ён",
        "gender": "M",
        "rank": "B",
        "img": "/assets/characters/kwak-doyoung.webp",
        "guild": "Нет",
        "age": 26,
        "status": "Активен",
        "loc": "Сеул",
        "contact": "Нет данных",
        "bio": "Охотник B-ранга, упоминается в официальной базе данных охотников."
    }
]